Document possible incompatibility
doctrine/data-fixtures pull request #380
Opened 2022-03-21 19:25 UTC by greg0ire

People are getting confused when getting "There is no active
transaction" from MySQL.

2022-03-21 19:27 UTC, greg0ire commented
@rtek please review.

2022-03-21 20:02 UTC, rtek requested changes

2022-03-21 20:02 UTC, rtek commented on README.md
> +in the database at the end of the loading. It delegates the purging to a
>that way the loading either succeeds or fails cleanly, meaning nothing is actually changed in the database ~at the end of the loading~ if the load fails.

2022-03-21 20:40 UTC, greg0ire commented on README.md
> +in the database at the end of the loading. It delegates the purging to a
Do you mean "if the loading fails"?

2022-03-21 20:41 UTC, rkorczykowski commented on README.md
> +in the database at the end of the loading. It delegates the purging to a
yessir other than that its good

2022-03-21 20:41 UTC, rtek commented on README.md
> +in the database at the end of the loading. It delegates the purging to a
yessir other than that its good.

2022-03-21 21:49 UTC, derrabus approved these changes

2022-03-21 22:02 UTC, SenseException approved these changes

2022-03-21 22:03 UTC, merged

2022-03-22 19:43 UTC, greg0ire commented on README.md
> +in the database at the end of the loading. It delegates the purging to a
Woops forgot to push the fix :man_facepalming: … that will be for another PR

2022-03-22 21:55 UTC, greg0ire commented on README.md
> +in the database at the end of the loading. It delegates the purging to a
https://github.com/doctrine/data-fixtures/pull/381