Update branch metadata
doctrine/data-fixtures pull request #499
Opened 2024-11-06 08:16 UTC by greg0ire

- 2.0.x is the new current branch
- 1.8.x is still maintained
- 2.1.x and 3.0.x exist

2024-11-06 23:18 UTC, SenseException requested changes

2024-11-06 23:18 UTC, SenseException commented on .doctrine-project.json
> +            "current": true
```suggestion
            "upcoming": true
```

2024-11-07 07:11 UTC, greg0ire commented on .doctrine-project.json
> +            "current": true
:facepalm:

2024-11-07 23:05 UTC, SenseException approved these changes

2024-11-07 23:05 UTC, merged